name: Build and Deploy
on:
    push:
        branches:
            - main 
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest  # 在最新的Ubuntu系统上运行
        steps: 
            - name: Checkout   # 检出代码-把GitHub仓库里的代码下载到当前环境
              uses: actions/checkout@v2

            - name: lock npm version  #设置node环境
              uses: actions/setup-node@v2
              with:
                  node-version: 24  #指定node版本
            
            - name: Install and Build
              run: |
                  npm i -g pnpm
                  pnpm run init
                  pnpm run docs:build
              env:
                  NODE_OPTIONS: --max_old_space_size=4096  #在执行Node.js命令前告诉它应该如何运行, 4G内存

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:                  
                  BRANCH: gh-pages   # 部署到gh-pages分支（GitHub Pages专用分支）
                  FOLDER: docs/.vuepress/dist  # 要部署的文件夹
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  #使用加密的访问令牌



            

