name: Build and Deploy
on:
    push:
        branches:
            - main 
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest  # 在最新的Ubuntu系统上运行
        steps: 
            - name: Checkout   # 检出代码-把GitHub仓库里的代码下载到当前环境
              uses: actions/checkout@v4

            - name: lock npm version  #设置node环境
              uses: actions/setup-node@v4
              with:
                  node-version: 24  #指定node版本
            
            - name: Install and Build
              run: |
                  npm i -g pnpm
                  pnpm run init
                  pnpm run docs:build
              env:
                  NODE_OPTIONS: --max_old_space_size=4096  #在执行Node.js命令前告诉它应该如何运行, 4G内存

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.4.2
              with:                  
                   branch: gh-pages
                   folder: dist
                   clean: true
                   git-config-name: 'GitHub Actions Bot'
                   git-config-email: '41898282+github-actions[bot]@users.noreply.github.com'
                   access_token: ${{ secrets.ACCESS_TOKEN }}  #使用加密的访问令牌



            

